permalink: /notes/:year/:month/:day/:title
markdown: kramdown
excerpt_separator: "<!--more-->"
title: Data Planes | Data Science Blog by Lisa Hehnke
description: In computing, data planes are the parts of a network that carry user traffic. DataPlanes.org builds on this idea by carrying information on data science and sharing reproducible code, aiming to contribute to the Open Science initiative.
url: http://lhehnke.github.io

#logo: logo.png

owner:
  name:           Lisa Hehnke
  avatar:         lhehnke_bw2.jpg
  email:          lisa.hehnke@googlemail.com
  twitter:        DataPlanes
  github:         lhehnke    

highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  hard_wrap: false
  
gems:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  