permalink: /notes/:year/:month/:day/:title
markdown: kramdown
title: lhehnke.github.io | Data Science Blog by Lisa Hehnke
description: Lisa Hehnke is a researcher turned data scientist, psych student, and aviation enthusiast from Hamburg, Germany. Her work mainly focuses on spatial analyses, computational social science, and serial killers.
url: http://lhehnke.github.io

#logo: logo.png



share-links-active:
  twitter: true
  facebook: true
  google: true
 linkedin: true
 
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
social-share: true # add social media sharing buttons to all blog posts

feed: true

owner:
  name:           Lisa Hehnke
  avatar:         lhehnke_bw2.jpg
  email:          lisa.hehnke@googlemail.com
  twitter:        N736PA_PHBUF
  github:         lhehnke    

google_analytics: UA-113150251-1

highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  hard_wrap: false
  
gems:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  